name: CI-good-spelling
permissions: write-all
on:
  push:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/upload-artifact@v4
      - name: test
        run: env
