name: Test Upload Artifact v4

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Test File
        run: |
          mkdir -p artifacts
          echo "This is a test file" > artifacts/test-file.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: artifacts/test-file.txt
