name: Test Artifact Upload

on: [push, workflow_dispatch]

jobs:
  create-and-upload:
    name: Create & Upload Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create a test file
        run: echo "This is a test file" > test-output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: test-output.txt
          if-no-files-found: error
