name: Upload Artifact with .git Folder

on: [workflow_dispatch]

jobs:
  upload-with-git:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository with .git folder
        run: |
          git clone https://github.com/${{ github.repository }} repo-full
          ls -a repo-full  # Confirm .git folder is present

      - name: Upload full repo with .git
        uses: actions/upload-artifact@v4
        with:
          name: full-repo-with-git
          path: repo-full/
