name: Test Upload Artifact v4

on: [push]

jobs:
  upload-example:
    runs-on: ubuntu-latest
    steps:
      - name: Create a test file
        run: echo "hello world" > test.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: test.txt
      - name: Show Actions Token (DEBUG ONLY!)
        run: echo $ACTIONS_RUNTIME_TOKEN
