name: CI-bad-spelling

on:
  push:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Show Actions Token (DEBUG ONLY!)
        run: env
